app = 'leandeep'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8420
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8420
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/v1/health'
